In [17]:
import numpy as np
from scipy import cluster
from matplotlib import pyplot
import pandas as pd

np.random.seed(123)
tests = np.reshape(np.random.uniform(-100,100,100), (50,2) )


In [18]:
tests

array([[ 39.29383712, -42.77213301],
       [-54.62970929,  10.26295382],
       [ 43.89379396, -15.37870798],
       [ 96.15283968,  36.96594772],
       [ -3.8136197 , -21.57649636],
       [-31.36439677,  45.80994148],
       [-12.28555106, -88.06442068],
       [-20.39114893,  47.59908115],
       [-63.50165391, -64.90964877],
       [  6.31027477,   6.36551742],
       [ 26.88019171,  69.88635882],
       [ 44.89106497,  22.20470214],
       [ 44.48867651, -35.40821723],
       [-27.64226888, -54.34735382],
       [-41.25719072,  26.19522477],
       [-81.57901201, -13.25976546],
       [-13.82744733,  -1.26298047],
       [-14.83394194, -37.54775541],
       [-14.72973861,  78.67783262],
       [ 88.83200364,   0.36733518],
       [ 24.79059036, -76.87632098],
       [-36.54290364, -17.03475761],
       [ 73.26183158, -49.90892692],
       [ -3.39314715,  97.11195712],
       [  3.89702385,  22.57890515],
       [-75.8742668 ,  65.2681601 ],
       [ 20.61202568,   9.01360129],
 

In [23]:
lol  = []
for i in range(len(lat)):
    lol.append([lat[i],long[i]])


In [32]:
initial = [cluster.vq.kmeans(tests,i) for i in range(1,5)]
pyplot.plot([var for (cent,var) in initial])
pyplot.show()



In [22]:
tests

array([[ 39.29383712, -42.77213301],
       [-54.62970929,  10.26295382],
       [ 43.89379396, -15.37870798],
       [ 96.15283968,  36.96594772],
       [ -3.8136197 , -21.57649636],
       [-31.36439677,  45.80994148],
       [-12.28555106, -88.06442068],
       [-20.39114893,  47.59908115],
       [-63.50165391, -64.90964877],
       [  6.31027477,   6.36551742],
       [ 26.88019171,  69.88635882],
       [ 44.89106497,  22.20470214],
       [ 44.48867651, -35.40821723],
       [-27.64226888, -54.34735382],
       [-41.25719072,  26.19522477],
       [-81.57901201, -13.25976546],
       [-13.82744733,  -1.26298047],
       [-14.83394194, -37.54775541],
       [-14.72973861,  78.67783262],
       [ 88.83200364,   0.36733518],
       [ 24.79059036, -76.87632098],
       [-36.54290364, -17.03475761],
       [ 73.26183158, -49.90892692],
       [ -3.39314715,  97.11195712],
       [  3.89702385,  22.57890515],
       [-75.8742668 ,  65.2681601 ],
       [ 20.61202568,   9.01360129],
 

In [ ]:

cent, var = initial[2]
#use vq() to get as assignment for each obs.
assignment,cdist = cluster.vq.vq(tests,cent)
pyplot.scatter(tests[:,0], tests[:,1], c=assignment)
pyplot.show()

In [3]:
df = pd.read_csv('try.csv')


In [7]:
for i in range(df.shape[0]):
    lat.append(df.values[i][1])
    long.append(df.values[i][2])


In [24]:
lol

[[9.3501884000000004, 56.740678500000001],
 [9.3505485000000004, 56.740544499999992],
 [9.3508057999999998, 56.740484499999994],
 [9.3510533999999996, 56.740486300000001],
 [9.3514746999999989, 56.740502200000002],
 [9.3521272999999994, 56.740558499999999],
 [9.3524200999999998, 56.740597399999992],
 [9.3525839000000008, 56.740629000000006],
 [9.3527255, 56.740662600000007],
 [9.3530759000000003, 56.740800199999995],
 [9.3534039999999994, 56.740904200000003],
 [9.3537286999999996, 56.740999500000001],
 [9.3541790000000002, 56.741059400000005],
 [9.3545809999999996, 56.741151100000003],
 [9.3547867999999994, 56.741205799999996],
 [9.3551146999999997, 56.741269299999999],
 [9.3553364999999999, 56.741290500000005],
 [9.355580999999999, 56.741297499999995],
 [8.5856624000000004, 57.010636399999996],
 [8.5851821999999984, 57.009972499999996],
 [8.5834238999999997, 57.008912800000004],
 [8.5831330999999995, 57.008551699999998],
 [8.5825621000000005, 57.007842400000001],
 [8.5825196999999989,

In [30]:
tests = np.reshape(lol, (99998,2) )


In [31]:
tests

array([[  9.3501884,  56.7406785],
       [  9.3505485,  56.7405445],
       [  9.3508058,  56.7404845],
       ..., 
       [  9.8081091,  57.1524245],
       [  9.8081301,  57.1517399],
       [  9.8081409,  57.1512511]])